---
title: "Comparison shape update"
author: "Nadim Saadi, Anne Hids, Joris Quik"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

source("baseScripts/initWorld.R")

```

# Explanation of update

[To be explained]

PlasticFADE (Plastic Fragmentation And Degradation in the Environment)

-   v_KdegDorC is changed to include the new plasticFADE input
    parameters.

There is now a choice of three types of degradation input to be used:
Kssdr, plasticFADE and the Default by setting kdeg directly for all the
relevant compartments based on seperately estimated half lifes.

This is done using `World$SetConst(DegApproach = "Default")`.

The plasticFADE model uses:

-   xxx

3 dec 2025: the script now compares to show nothing has changed, but
verification of plasticFADE evaluation of data and comparison to
expected kdeg half life outcomes is still needed.

```{R Specify directories, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

# InstallSBoo (Release_SBoo = NA, # tag for release use NA for branch
#              Release_SBooScripts = NA, # tag for release use NA for branch
#              devBranch_SBoo = "Runoff_update_clean",
#              devBranch_SBooScripts = "Runoff_MPinterception",
#              Temp_Folder = "C:/Temp" # an existing folder where SimpleBox is to be installed
# )

InstallSBoo(Release_SBoo = NA, # tag for release use NA for branch
            Release_SBooScripts = NA, # tag for release use NA for branch
            devBranch_SBoo = "development",
            devBranch_SBooScripts = "development",
            Temp_Folder = NULL # an existing folder where SimpleBox is to be installed
)

```

As this update was only implemented for microplastics and tyre road wear
particles, we will test for these substances. To be sure nothing changed
for the other substances, we will also test one other substance.

```{R Specify substance, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
substance_names <- c("microplastic", "TRWP", "1-aminoanthraquinone","nAg_10nm") 
substances <- read.csv("data/Substances.csv")
substances <- substances |>
  filter(Substance %in% substance_names)
```

```{R, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
this_kaas <- data.frame()
# this_variables <- data.frame()
for(substanceK in substances$Substance){
  # Get the substance type
  substance <- substanceK
      source("baseScripts/initWorld.R")

  kaas <- World$kaas |>
    # filter(process == "k_Runoff") |>
    mutate(Substance = substance)
  
  # SetVel <- World$fetchData("SettlingVelocity") |> 
    # mutate(Substance = substance)
  # this_variables <- rbind(this_variables,SetVel)
  # this_variables <- cross_join(SetVel)
  this_kaas <- rbind(this_kaas, kaas)
}

```

Do the same for the other implementation.

```{R Clean environment again, include=FALSE}
rm(list = ls()[sapply(ls(), function(x) is.function(get(x)))])
```

```{R Run SB and get advection ks for FLux_work branch, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

other_kaas <- data.frame()
  
for(substanceK in substances$Substance){
  Temp_Folder=NULL
  substance = substanceK
  
  source("baseScripts/initWorldOther.R")
  
  kaas <- World$kaas |>
    # filter(process == "k_Runoff") |>
    mutate(Substance = substance)
  
  other_kaas <- rbind(other_kaas, kaas)
}

```

## Verification of previous and new implementation

```{R Calculate the differences between ks, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
common_cols <- setdiff(intersect(colnames(this_kaas), colnames(other_kaas)), "k")

kaas_comparison <- merge(this_kaas, other_kaas, by=common_cols, suffixes = c("_Old", "_New"))

kaas_comparison <- kaas_comparison |>
  mutate(diff = k_New-k_Old) |> # If this number is positive, the New_k is higher than the Old_k (higher advection rate with new method)
  mutate(rel_diff = diff/k_New)

changed_kaas <- kaas_comparison |>
 filter(diff != 0) |>
    # filter(abs(rel_diff) > 0.001) |>
  mutate(full_name = paste0("From ", fromSubCompart, "_", fromScale, " to ", toSubCompart, "_", toScale))
changed_kaas
```

As can be seen in the figures below, the new degradation rate constants
for `r paste(substances$Substance)[2]`, have a very large difference,
max `r max(abs(unique(changed_kaas$rel_diff)))*(-100)` % larger compared
to the previous default kdeg value's. The figures below also show this
and and that the code still works as expected for the other compounds
for which no Kssdr is defined. The larger degradation rates for
microplastics is as expected due to the Kssdr implementation. Further
examples should illustrate the validity of this modification, e.g.
comparing to measuresments etc.

```{R Plot the differences between ks, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
all_diffs <- changed_kaas |>
  mutate(fromname = paste0(fromSubCompart, "_", fromScale)) |>
  mutate(toname = paste0(toSubCompart, "_", toScale))

for(i in unique(all_diffs$Substance)){
  diffs_substance <- all_diffs |>
    filter(Substance == i)
  
  absdif_plot <- ggplot(diffs_substance, mapping = aes(x = toname, y = fromname, color = diff)) + 
    geom_point() + 
    labs(
      title = "Difference between old and new k's",
      subtitle = i,
      x = "To",  
      y = "From",  
      color = "Difference"  
    ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      panel.grid.major = element_line(linewidth = 0.2, color = "gray90"),  
      panel.background = element_blank() 
    )
  
  print(absdif_plot)
  
  reldif_plot <- ggplot(diffs_substance, mapping = aes(x = toname, y = fromname, color = rel_diff)) + 
    geom_point() + 
    labs(
      title = "Relative difference between old and new k's",
      subtitle = i,
      x = "To",  
      y = "From",  
      color = "Relative difference"  
    ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      panel.grid.major = element_line(size = 0.2, color = "gray90"),
      panel.background = element_blank()  
    )
  print(reldif_plot)
}
```
