---
title: "Comparison runoff update"
author: "Anne Hids, Nadim Saadi, Joris Quik"
date: "2025-05-27"
output: github_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("baseScripts/initWorld.R")
```

# Explanation of update

The previous function for calculating the runoff rate for microplastics
was taken from SimpleBox4Plastics in MS Excel. This function included
runoff and erosion. In this calculation it is assumed that all
microplastics are transported from soil compartments to water
compartments by runoff. In reality however, some of the microplastics
are trapped or slowed down by vegetation present on the soil.

To avoid overestimation of the runoff rate, an interception rate was
added. This rate represents the fraction of microplastics intercepted by
the vegetation on soil. The default value of kinterception is 0.9715,
which is the average between the interception at high, medium and low
density vegetation as found by Han et al. (2022)

This function is based on Louvet et al. (in prep).

Old function:

$(Runoff * f_CORRsoil(VertDistance, relevant_depth_s, penetration_depth_s)) / Volume * to.FracROWatComp$

New function:

$(Runoff * f_CORRsoil(VertDistance, relevant_depth_s, penetration_depth_s)) / Volume * to.FracROWatComp * (1-IntrcptFrac)$

# Change in k values for runoff flows

<!-- TO DO: fetch development at a certain date instead of most recent version. This would ensure consequent outcomes of this comparison, no matter when the script is run. -->

```{R Specify directories, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

# InstallSBoo (Release_SBoo = NA, # tag for release use NA for branch
#              Release_SBooScripts = NA, # tag for release use NA for branch
#              devBranch_SBoo = "Runoff_update_clean",
#              devBranch_SBooScripts = "Runoff_MPinterception",
#              Temp_Folder = "C:/Temp" # an existing folder where SimpleBox is to be installed
# )

InstallSBoo(Release_SBoo = NA, # tag for release use NA for branch
            Release_SBooScripts = NA, # tag for release use NA for branch
            devBranch_SBoo = "development",
            devBranch_SBooScripts = "development",
            Temp_Folder = NULL # an existing folder where SimpleBox is to be installed
)

# Define branches to test
Comparison <- c("development", "ThisOne")

# Specify file paths for saving results
result_files <- paste0("results_", Comparison, ".rds")

# Directory of your Git repository (modify this path to the correct repository location)
#script_dir <-getwd()
#repo_dir <- file.path(getwd(), "..", "SBoo")

```

As this update was only implemented for microplastics and tyre road wear
particles, we will test for these substances. To be sure nothing changed
for the other substances, we will also test one other substance.

```{R Specify substance, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
substance_names <- c("microplastic", "TRWP", "1-aminoanthraquinone") 
substances <- read.csv("data/Substances.csv")
substances <- substances |>
  filter(Substance %in% substance_names)
```

```{R Switch to SBoo Development branch, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
# Switch to the correct Git directory
# setwd(repo_dir)

# Checkout the branch
# branch <- branches[1]
# message("Switching to branch: ", branch)
# system(paste("git checkout -f ", branch))
# system("git pull", intern = TRUE)  # Ensure the branch is up-to-date
  
# setwd(script_dir)
```

```{R Run SB and get advection ks for development, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
this_kaas <- data.frame()

for(substanceK in substances$Substance){
  # Get the substance type
  substance <- substanceK
      source("baseScripts/initWorld.R")

  kaas <- World$kaas |>
    # filter(process == "k_Runoff") |>
    mutate(Substance = substance)
  
  this_kaas <- rbind(this_kaas, kaas)
}

```

Do the same for the other implementation.

```{R Clean environment again, include=FALSE}
rm(list = ls()[sapply(ls(), function(x) is.function(get(x)))])
```

```{R Switch to SBoo Flux_work branch, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
# Switch to the correct Git directory
# setwd(repo_dir)

# Checkout the branch
# branch <- branches[2]
# message("Switching to branch: ", branch)
# system(paste("git checkout -f ", branch))
# system("git pull", intern = TRUE)  # Ensure the branch is up-to-date
  
# setwd(script_dir)


```

```{R Run SB and get advection ks for FLux_work branch, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}

other_kaas <- data.frame()
  
for(substanceK in substances$Substance){
Temp_Folder=NULL
substance = substanceK

source("baseScripts/initWorldOther.R")

  kaas <- World$kaas |>
    # filter(process == "k_Runoff") |>
    mutate(Substance = substance)
  
  other_kaas <- rbind(other_kaas, kaas)
}

```

## Compare the k values for each of the substances

```{R Calculate the differences between ks, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
common_cols <- setdiff(intersect(colnames(this_kaas), colnames(other_kaas)), "k")

kaas_comparison <- merge(this_kaas, other_kaas, by=common_cols, suffixes = c("_Old", "_New"))

kaas_comparison <- kaas_comparison |>
  mutate(diff = k_New-k_Old) |> # If this number is positive, the New_k is higher than the Old_k (higher advection rate with new method)
  mutate(rel_diff = diff/k_New)

changed_kaas <- kaas_comparison |>
  filter(diff != 0) |>
  mutate(full_name = paste0("From ", fromSubCompart, "_", fromScale, " to ", toSubCompart, "_", toScale))
```

As can be seen in the figures below, the new runoff rates for
microplastics and TRWP are about
`r round(abs(min(unique(changed_kaas$rel_diff))), 0)` times lower than
in the previous version. For other substances k_Runoff remains
unchanged.

```{R Plot the differences between ks, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
all_diffs <- kaas_comparison |>
  mutate(fromname = paste0(fromSubCompart, "_", fromScale)) |>
  mutate(toname = paste0(toSubCompart, "_", toScale))

for(i in unique(all_diffs$Substance)){
  diffs_substance <- all_diffs |>
    filter(Substance == i)
  
  absdif_plot <- ggplot(diffs_substance, mapping = aes(x = toname, y = fromname, color = diff)) + 
    geom_point() + 
    labs(
      title = "Difference between old and new runoff k's",
      subtitle = i,
      x = "To",  
      y = "From",  
      color = "Difference"  
    ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      panel.grid.major = element_line(size = 0.2, color = "gray90"),  
      panel.background = element_blank() 
    )
  
  print(absdif_plot)
  
  reldif_plot <- ggplot(diffs_substance, mapping = aes(x = toname, y = fromname, color = rel_diff)) + 
    geom_point() + 
    labs(
      title = "Relative difference between old and new runoff k's",
      subtitle = i,
      x = "To",  
      y = "From",  
      color = "Relative difference"  
    ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1), 
      panel.grid.major = element_line(size = 0.2, color = "gray90"),
      panel.background = element_blank()  
    )
  print(reldif_plot)
}
```
