---
title: "Verification"
author: "Valerie de Rijk, Anne Hids, Joris Quik"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::knit_meta()
knitr::opts_chunk$set(
	eval = FALSE,
	fig.height = 8,
	fig.width = 14,
	include = FALSE
)
projectRoot <- paste(getwd(), "..", "..", "..", "..", sep = "/")
knitr::opts_knit$set(root.dir = projectRoot) #assuming vignette is in a direct subfolder of the project
options(dplyr.summarise.inform=FALSE)
knitr::opts_chunk$set(echo = TRUE, fig.width = 14, fig.height = 8)

library(openxlsx)
library(tidyverse)
library(ggplot2)
```

## Define the comparison type
```{r}
compare_to <- "Excel"
# compare_to <- "Previous_R_version"

```

## Define substances
```{r, warning=FALSE, message=FALSE}
Potential_substances <- c("1-aminoanthraquinone", # no class
                          "1-HYDROXYANTHRAQUINONE", # acid
                          "1-Hexadecanamine, N,N-dimethyl-", # base
                          "Sb(III)", # metal
                          "microplastic", # microplastic
                          "nAg_10nm" # particulate
                          ) 
```

## Perform verification
```{r, warning=FALSE, message=FALSE}
for(i in Potential_substances){
  substance <- i
  test_value <- "TRUE"
  source("vignettes/Development/Verification.R")
}
```


```{r}

```

