---
title: "Overview documentation"
author: "JQ"
date: "2023-08-22"
output: github_document
editor_options: 
  chunk_output_type: console
---

This document is used to track the testing and verification of vignettes. There are two types of vignettes. Vignettes in the "SBooScripts/vignettes" folder with chapter numbers describe processes in SimpleBox. Vignettes in "SBooscripts/vignettes/Development" are meant to support developers of SimpleBox and describe e.g. best practices for debugging.

Please add any new vignette to the overview table below. Indicate in the "Initial run" column whether an initial run of the script has been successfully performed, and whether it is thus ready for testing. The verification column can be used to indicate whether testing has been performed or is currently in progress.

# Progress overview process vignettes

| Vignette                                   | Initial run | Verification | Date       | Related Issue \# |
|--------------|--------------|--------------|--------------|----------------|
| 3.0 Characteristics of the compound.Rmd    | done        | in progress             |            |  #57                |
| 3.2 Particle Characteristics.Rmd           | done        |              |            |                  |
| 4.0 partitioning.Rmd                       | done        | done         | 2023-08-25 |                  |
| 5.0 Characteristics of the Environment.Rmd | done        |              |            |                  |
| 5.1 Area.Rmd                               | done        | done             | 2024-01-22           |                  |
| 5.3 FRACwas.Rmd                            | done        |  in progress            |            |  #17                |
| 5.4 Advection.Rmd                          |             |              |            |                  |
| 6.0 Removal.Rmd                            | done        |              |            |                  |
| 7.1.1 Deposition Conventional.Rmd          |             |              |            |                  |
| 7.1.2 Deposition Particulate.Rmd           | done        |              |            |                  |
| 7.1.3 sedimentation.Rmd                    | done        |              |            |                  |
| 7.2 DiffusionProcesses.Rmd                 | done        |              |            |                  |
| 7.3 OtherIntermedia.Rmd                    | done        |              |            |                  |
| 9.0 HeteroAglomeration.Rmd                 | done        |              |            |                  |
|                                            |             |              |            |                  |

# Progress overview development vignettes

| Vignette               | Initial run | Verification | Date | Related Issue \# |
|------------------------|-------------|--------------|------|------------------|
| Advective Flows.Rmd    |             |              |      |                  |
| ClassicSolve.Rmd       |             |              |      |                  |
| CSVdata.Rmd            |             |              |      |                  |
| Debugging.Rmd          |             |              |      |                  |
| DefaultCalc.Rmd        |             |              |      |                  |
| defaults.Rmd           |             |              |      |                  |
| FirstOrdM.Rmd          |             |              |      |                  |
| FirstVars.Rmd          |             |              |      |                  |
| METAdata.Rmd           |             |              |      |                  |
| processFlow.Rmd        |             |              |      |                  |
| SBdemo.Rmd             |             |              |      |                  |
| start.Rmd              |             |              |      |                  |
| testAzure.Rmd          |             |              |      |                  |
| testRainDropRadius.Rmd |             |              |      |                  |
| TraceTrack.Rmd         |             |              |      |                  |
