---
title: "Figures"
author: "Anne Hids"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages

```{R load packages}
library(tidyverse)
library(readxl)
library(scales)
```

```{R Load data}
path <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/MOMENTUM2/PlotData/NewSBoo/"

data_date <- "20250625" # The data of the data for which to make the figures

if(exists(paste0("Concentrations_2019_", data_date, ".RData"))){
  file_names <- c(
  paste0("Concentrations_2019_", data_date, ".RData"),
  paste0("All_variables_", data_date, ".RData")
  )
  # Load all files in a loop
  for (file in file_names) {
    load(file = paste0(path, file))
  }
} else {
  per_polymer_path <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/MOMENTUM2/Output_per_polymer"
  
  Concentrations_2019 <- data.frame()
  All_variables <- data.frame()
  
  files <- list.files(per_polymer_path)
  files_date <- grep(data_date, files)
  files <- files[files_date]
  concentration_files <- grep("Concentrations_2019_", files)
  concentration_files <- files[concentration_files]
  
  variable_files <- grep("All_variables_", files)
  variable_files <- files[variable_files]
  
  for(i in variable_files){
    load(paste0(per_polymer_path, "/", i))
    All_variables <- rbind(All_variables, all_variables)
  }

  for(j in concentration_files){
    load(paste0(per_polymer_path, "/", j))
    Concentrations_2019 <- rbind(Concentrations_2019, concentrations_2019)
  }
}
```

Load and prepare SimpleBox outcome data

```{R load SimpleBox data}
## Define paths 
figurefolder <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/MOMENTUM2/Figures/" # Define figure folder path
abs_path_Measurements <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/LEONT_TNO_measurements_clean.xlsx" # Define path to LEON-T measurement data
```

```{R set plot parameters}
# Create a plot theme
plot_theme <-  theme(
  axis.title.x = element_text(size = 30),    
  axis.title.y = element_text(size = 30),    
  axis.text.x = element_text(size = 28, angle = 65, hjust = 1),     
  axis.text.y = element_text(size = 28),
  legend.text = element_text(size = 28),
  title = element_text(size=30),
  panel.background = element_rect(fill = "white"),  # White background
  panel.grid.major = element_line(color = "lightgrey", size = 1),  # Major grid lines in light grey
  panel.grid.minor = element_line(color = "lightgrey", size = 1)
)

Source_type_colors = c("SimpleBox" = "#00c0AF", 
                            "Measurement_NL" = "#481567FF", 
                            "Measurement_Europe" = "#F8766D")

Measurement_type_colors = c("Measurement_NL" = "#481567FF", 
                            "Measurement_Europe" = "#F8766D")

select_year <- 2019
```

# Prepare data for plotting
Convert mass to particles for comparison to measurements. 

Also filter out any RUN/Polymer combinations that have a RadS outside the detection limits of the measurements.

## All polymers
```{R convert mass to particles concentration}

concentrations_2019 <- Concentrations_2019 |>
  rename(RUN = RUNs)

concentrations_2019 <- concentrations_2019 |>
  filter(Polymer != "General")

concentrations_2019_general <- Concentrations_2019 |>
  filter(Polymer == "General")

all_variables <- All_variables |>
  filter(Polymer != "General") |>
  distinct()

measurements_particles <- read_xlsx("/rivm/r/E121554 LEON-T/03 - uitvoering WP3/MOMENTUM2/MOMENTUM2_measurements.xlsx", sheet = "Particle Data") |>
  mutate(Scale = str_replace(Scale, "Regional", "NL"),
         Scale = str_replace(Scale, "Continental", "Europe"))

lower_limit <- min(na.omit(measurements_particles$lower_detection_limit_um)) * 1000
upper_limit <- max(measurements_particles$upper_detection_limit_um) * 1000

# Get run numbers between the lower and upper limit
limit_runs <- all_variables |>
  filter(VarName == "RadS" | VarName == "RhoS") |>
  select(VarName, Polymer, RUN, value) |>
  pivot_wider(names_from = "VarName", values_from = "value") |>
  filter(RadS >= lower_limit) |>
  filter(RadS <= upper_limit) 

rad_rho_filtered <- limit_runs |>
  rename(rad_nm = RadS) |>
  rename(rho_kg_m3 = RhoS) |>
  mutate(rad_m = rad_nm*10^-9) |>
  mutate(volume_m3 = (4/3)*pi*rad_m^3) |>
  mutate(mass_per_particle_kg = volume_m3*rho_kg_m3)

mass_conc_C_R_2019_per_polymer_SI <- concentrations_2019 |>
  mutate(Concentration = case_when(
    Unit == "g/kg w" ~ Concentration/1000,
    Unit == "g/m3" ~ Concentration/1000,
    Unit == "g/L" ~ Concentration
  )) |>
  mutate(Unit = case_when(
    Unit == "g/kg w" ~ "kg/kg dw",
    Unit == "g/m3" ~ "kg/m3",
    Unit == "g/L" ~ "kg/m3"
  )) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")"))

particle_conc_C_R_2019_per_polymer_filtered <- mass_conc_C_R_2019_per_polymer_SI |>
  filter(year == select_year) |>
  left_join(rad_rho_filtered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  mutate(Concentration = Concentration/mass_per_particle_kg) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "#/kg dw",
    Unit == "kg/m3" ~ "#/m3")) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") 

particle_conc_C_R_2019_summed_over_polymer_filtered <- particle_conc_C_R_2019_per_polymer_filtered |>
  group_by(RUN, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration)) |>
  ungroup()
```

## Microplastics in general
```{R convert mass to particles concentration}

concentrations_2019_general <- Concentrations_2019 |>
  rename(RUN = RUNs) |>
  filter(Polymer == "General")

all_variables_general <- All_variables |>
  filter(Polymer == "General") |>
  distinct()

# Get run numbers between the lower and upper limit
limit_runs_general <- all_variables_general |>
  filter(VarName == "RadS" | VarName == "RhoS") |>
  select(VarName, Polymer, RUN, value) |>
  pivot_wider(names_from = "VarName", values_from = "value") |>
  filter(RadS >= lower_limit) |>
  filter(RadS <= upper_limit) 

rad_rho_filtered_general <- limit_runs_general |>
  rename(rad_nm = RadS) |>
  rename(rho_kg_m3 = RhoS) |>
  mutate(rad_m = rad_nm*10^-9) |>
  mutate(volume_m3 = (4/3)*pi*rad_m^3) |>
  mutate(mass_per_particle_kg = volume_m3*rho_kg_m3)

mass_conc_C_R_2019_per_polymer_SI_general <- concentrations_2019_general |>
  mutate(Concentration = case_when(
    Unit == "g/kg w" ~ Concentration/1000,
    Unit == "g/m3" ~ Concentration/1000,
    Unit == "g/L" ~ Concentration
  )) |>
  mutate(Unit = case_when(
    Unit == "g/kg w" ~ "kg/kg dw",
    Unit == "g/m3" ~ "kg/m3",
    Unit == "g/L" ~ "kg/m3"
  )) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")"))

particle_conc_C_R_2019_per_polymer_filtered_general <- mass_conc_C_R_2019_per_polymer_SI_general |>
  filter(year == select_year) |>
  left_join(rad_rho_filtered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  mutate(Concentration = Concentration/mass_per_particle_kg) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "#/kg dw",
    Unit == "kg/m3" ~ "#/m3")) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") 

particle_conc_C_R_2019_summed_over_polymer_filtered_general <- particle_conc_C_R_2019_per_polymer_filtered_general |>
  group_by(RUN, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration)) |>
  ungroup()
```

# Summed over polymers

## Continental scale comparisons

```{R Make figure comparing SB outcomes to particle measurements for all polymers}
# Get measured concentrations
measurements_formatted <- measurements_particles |> 
  mutate(source = paste0("Measurement_", Scale)) |>
  rename(Concentration = concentration,
         Unit = concentration_unit) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(Concentration, SubCompartName, source) 

particle_conc_C_2019_summed_over_polymer_filtered <- particle_conc_C_R_2019_summed_over_polymer_filtered |>
  filter(Scale == "Continental")

particle_plot_data <- bind_rows(particle_conc_C_R_2019_summed_over_polymer_filtered, measurements_formatted)
Figure <- ggplot(particle_plot_data, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = particle_plot_data %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = particle_plot_data |> filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at continental scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_continental_particle_size_filtered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

Particle figure with all polymers but not filtered for size

```{R The same figure but not filtered for size}

# Get run numbers between the lower and upper limit
rad_rho_unfiltered <- all_variables |>
  filter(VarName == "RadS" | VarName == "RhoS") |>
  select(VarName, Polymer, RUN, value) |>
  pivot_wider(names_from = "VarName", values_from = "value") |>
  rename(rad_nm = RadS) |>
  rename(rho_kg_m3 = RhoS) |>
  mutate(rad_m = rad_nm*10^-9) |>
  mutate(volume_m3 = (4/3)*pi*rad_m^3) |>
  mutate(mass_per_particle_kg = volume_m3*rho_kg_m3)

particle_conc_C_R_2019_per_polymer <- mass_conc_C_R_2019_per_polymer_SI |>
  filter(year == select_year) |>
  left_join(rad_rho_unfiltered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  mutate(Concentration = Concentration/mass_per_particle_kg) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "#/kg dw",
    Unit == "kg/m3" ~ "#/m3")) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") 

#particles_conc_continental_regional_polymer_unfiltered 
particles_conc_C_R_2019_per_polymer_unfiltered <- mass_conc_C_R_2019_per_polymer_SI |>
  filter(year == select_year) |>
  left_join(rad_rho_unfiltered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  mutate(Concentration = Concentration/mass_per_particle_kg) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "#/kg dw",
    Unit == "kg/m3" ~ "#/m3")) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") 

particles_conc_C_R_2019_summed_over_polymer_unfiltered <- particles_conc_C_R_2019_per_polymer_unfiltered |>
  group_by(RUN, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration)) |>
  ungroup()

# Get measured concentrations
measurements_formatted <- measurements_particles |> 
  mutate(source = paste0("Measurement_", Scale)) |>
  rename(Concentration = concentration,
         Unit = concentration_unit) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(Concentration, SubCompartName, source) 

particles_conc_continental_polymer_unfiltered <- particles_conc_C_R_2019_summed_over_polymer_unfiltered |>
  filter(Scale == "Continental")

particle_plot_data <- bind_rows(particles_conc_continental_polymer_unfiltered, measurements_formatted)
Figure <- ggplot(particle_plot_data, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = particle_plot_data %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = particle_plot_data %>% filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at continental scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations not filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_continental_particle_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

## Regional scale comparisons

Convert mass to particles for comparison to measurements. 

Also filter out any RUN/Polymer combinations that have a RadS outside the detection limits of the measurements.

```{R convert mass to particles concentration}
particle_conc_R_2019_summed_over_polymer_filtered <- particle_conc_C_R_2019_summed_over_polymer_filtered |>
  filter(Scale == "Regional")
```

```{R Make figure comparing SB outcomes to particle measurements for all polymers}
# Get measured concentrations
measurements_formatted <- measurements_particles |> 
  mutate(source = paste0("Measurement_", Scale)) |>
  rename(Concentration = concentration,
         Unit = concentration_unit) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(Concentration, SubCompartName, source) 

particle_plot_data <- bind_rows(particle_conc_R_2019_summed_over_polymer_filtered, measurements_formatted)

Figure <- ggplot(particle_plot_data, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = particle_plot_data %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = particle_plot_data |> filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at regional scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_regional_particle_size_filtered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

Particle figure with all polymers but not filtered for size

```{R The same figure but not filtered for size}
particles_conc_regional_polymer_unfiltered <- particles_conc_C_R_2019_summed_over_polymer_unfiltered |>
  filter(Scale == "Regional")

# Get measured concentrations
measurements_formatted <- measurements_particles |> 
  mutate(source = paste0("Measurement_", Scale)) |>
  rename(Concentration = concentration,
         Unit = concentration_unit) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(Concentration, SubCompartName, source) 

particle_plot_data <- bind_rows(particles_conc_regional_polymer_unfiltered, measurements_formatted)
Figure <- ggplot(particle_plot_data, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = particle_plot_data %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = particle_plot_data %>% filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at regional scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations not filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_regional_particle_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

Comparison mass data to SB data at regional scale

```{R Make figure comparing SB outcomes to mass measurements for all polymers}
measurements_mass <- read_xlsx("/rivm/r/E121554 LEON-T/03 - uitvoering WP3/MOMENTUM2/MOMENTUM2_measurements.xlsx", sheet = "Mass Data") |>
  filter(source != "LEON-T measurement") |>
  mutate(Scale = str_replace(Scale, "Regional", "NL"),
         Scale = str_replace(Scale, "Continental", "Europe"))

# Get measured concentrations
measurements_formatted <- measurements_mass |> 
  mutate(source = paste0("Measurement_", Scale)) |>
  rename(Concentration = concentration,
         Unit = concentration_unit) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  select(Concentration, SubCompartName, source) 

mass_conc_regional_size_filtered <- mass_conc_C_R_2019_per_polymer_SI |>
  filter(year == select_year) |>
  filter(Scale == "Regional") |>
  left_join(rad_rho_filtered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") |>
  group_by(RUN, SubCompart, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration)) |>
  mutate(Concentration = Concentration*1*10^9) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "µg/kg dw",
    Unit == "kg/m3" ~ "µg/m^3"
  )) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  ungroup()

mass_plot_data_filtered <- bind_rows(mass_conc_regional_size_filtered, measurements_formatted)

mass_conc_regional_size_unfiltered <- mass_conc_C_R_2019_per_polymer_SI |>
  filter(year == select_year) |>
  filter(Scale == "Regional") |>
  left_join(rad_rho_unfiltered, by = c("RUN", "Polymer")) |>
  filter(!is.na(rad_nm)) |>
  select(RUN, year, Scale, SubCompart, Polymer, Concentration, Unit, SubCompartName) |>
  mutate(source = "SimpleBox") |>
  group_by(RUN, SubCompart, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration)) |>
  mutate(Concentration = Concentration*1*10^9) |>
  mutate(Unit = case_when(
    Unit == "kg/kg dw" ~ "µg/kg dw",
    Unit == "kg/m3" ~ "µg/m^3"
  )) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")")) |>
  ungroup()

mass_plot_data_unfiltered <- bind_rows(mass_conc_regional_size_unfiltered, measurements_formatted)

Figure <- ggplot(mass_plot_data_filtered, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = mass_plot_data_filtered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = mass_plot_data_filtered %>% filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at regional scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_regional_mass_size_filtered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)

Figure <- ggplot(mass_plot_data_unfiltered, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = mass_plot_data_unfiltered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = mass_plot_data_unfiltered %>% filter(source %in% c("Measurement_NL", "Measurement_Europe")), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations at regional scale, ", as.character(select_year)),
    subtitle = paste0("Modeled concentrations not filtered for detection limit of measurements"),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "All_polymers_regional_mass_size_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

# Tyre wear

Compare modeled TW concentrations with measured concentrations. 

```{R Figure comparing TW concentrations with measurements}
source("vignettes/CaseStudies/LEON-T/f_plot_functions.R")
LEONT_TWP_data <- prep_LEONT_data(abs_path_Measurements) 

subcomparts <- unique(LEONT_TWP_data$SubCompart)

mass_conc_SB_data_TW <- concentrations_2019 |>
  filter(Scale == "Regional") |>
  filter(Polymer %in% c("NR", "SBR")) |>
  group_by(RUN, year, Scale, SubCompart, Unit) |>
  summarise(Concentration = sum(Concentration))

# Prepare SimpleBox data for plotting
mass_conc_SB_data_TW2 <- mass_conc_SB_data_TW |>
  mutate(Concentration = case_when(
    Unit == "g/kg w" ~ Concentration*1000,
    Unit == "g/m3" ~ Concentration*1000000,
    Unit == "g/L" ~ Concentration*1000000,
    TRUE ~ Concentration
  )) |>
  mutate(Unit = case_when(
    Unit == "g/kg w" ~ "mg/g dw",
    Unit == "g/m3" ~ "µg/m^3",
    Unit == "g/L" ~ "µg/L",
    TRUE ~ Unit
  )) |>
  mutate(SubCompartName = paste0(SubCompart, " (", Unit, ")" )) |>
  mutate(Polymer = "SBR + NR") |>
  mutate(source = "SimpleBox") |>
  filter(SubCompart %in% subcomparts) |>
  mutate(Locatie = "SimpleBox") |>
  select(colnames(LEONT_TWP_data)) 

# Make plot comparing LEONT and SB data
LEONT_SB_SBR_NR <- bind_rows(LEONT_TWP_data, mass_conc_SB_data_TW2) |>
  filter(Polymer == "SBR + NR") 

Figure <- ggplot(LEONT_SB_SBR_NR, aes(x = SubCompartName, y = Concentration, col=source)) +  
  geom_violin(data = LEONT_SB_SBR_NR %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = LEONT_SB_SBR_NR %>% filter(source == "LEON-T measurement"), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = c("SimpleBox" = "#00c0AF", "LEON-T measurement" = "#F8766D")) +
  scale_color_manual(values = c("LEON-T measurement" = "#F8766D")) +
  labs(
    title = paste0("SBR + NR concentrations at Regional scale, ", as.character(select_year)),
    x = "",
    y = "Concentration"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "Tyre_wear_mass_regional_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

# Per polymer

Read in the measurements
```{R}
ftir_data <- read_xlsx("/rivm/n/hidsa/Documents/GitLab/exposuredata/Exposure_data.xlsx")
concentration_per_polymer <- ftir_data |>
  group_by(location, Identification, MP_m3) |>
  summarise(
    concentration = n()
  )

found_polymers <- unique(concentration_per_polymer$Identification)

concentration_per_polymer_identified <- concentration_per_polymer |>
  mutate(Polymer = case_when(
    str_detect(Identification, "PET") ~ "PET",
    str_detect(Identification, "PA") ~ "PA",
    str_detect(Identification, "PU") ~ "PUR",
    str_detect(Identification, "PE") ~ "PE",
    str_detect(Identification, "PP") ~ "PP",
    str_detect(Identification, "PS") ~ "PS",
    str_detect(Identification, "PVC") ~ "PVC",
    str_detect(Identification, "PMMA") ~ "PMMA",
    str_detect(Identification, "Rubber") ~ "RUBBER",
    str_detect(Identification, "PC") ~ "PC",
    TRUE ~ "OTHER"
  )) |>
  group_by(Polymer, MP_m3, location) |>
  summarise(concentration = sum(concentration)) |>
  ungroup() 

concentration_sums <- concentration_per_polymer_identified |>
  group_by(location, MP_m3) |>
  mutate(concentration_sum = sum(concentration)) |>
  mutate(polymer_fraction = concentration/concentration_sum) |>
  mutate(MP_m3_new = round((MP_m3*polymer_fraction),0)) |>
  ungroup() |>
  select(location, MP_m3_new, Polymer) |>
  rename(Concentration = MP_m3_new)
```

Make plot per polymer for regional scale
```{R}
polymers <- unique(concentration_sums$Polymer)

particle_conc_regional_per_polymer_unfiltered <- particles_conc_C_R_2019_per_polymer_unfiltered |>
  filter(Scale == "Regional") |>
  filter(SubCompart == "river") |>
  mutate(source = "SimpleBox") |>
  mutate(Polymer = case_when(
    Polymer == "LDPE" ~ "PE",
    Polymer == "HDPE" ~ "PE",
    Polymer == "NR" ~ "RUBBER",
    Polymer == "SBR" ~ "RUBBER",
    TRUE ~ Polymer
  )) |>
  group_by(RUN, Polymer, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration))

particle_conc_regional_per_polymer_filtered <- particle_conc_C_R_2019_per_polymer_filtered |>
  filter(Scale == "Regional") |>
  filter(SubCompart == "river") |>
  mutate(source = "SimpleBox") |>
  filter(Polymer %in% polymers) |>
  mutate(Polymer = case_when(
    Polymer == "LDPE" ~ "PE",
    Polymer == "HDPE" ~ "PE",
    Polymer == "NR" ~ "RUBBER",
    Polymer == "SBR" ~ "RUBBER",
    TRUE ~ Polymer
  )) |>
  group_by(RUN, Polymer, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration))

measured_concentrations_polymer <- concentration_sums |>
  mutate(SubCompart = "river",
         Unit = "#/m3",
         SubCompartUnit = paste0(SubCompart, " (", Unit, ")"),
         source = "Measurement_NL")  |>
  filter(Polymer %in% polymers)

# Prepare plot data
per_polymer_filtered <- bind_rows(particle_conc_regional_per_polymer_filtered, measured_concentrations_polymer)
per_polymer_unfiltered <- bind_rows(particle_conc_regional_per_polymer_unfiltered, measured_concentrations_polymer)

Figure <- ggplot(per_polymer_filtered, aes(x = Polymer, y = Concentration, col=source)) +  
  geom_violin(data = per_polymer_filtered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = per_polymer_filtered %>% filter(source == "Measurement_NL"), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations in river at regional scale, ", as.character(select_year)),
    subtitle = "Modeled concentrations filtered for detection limit of measurements",
    x = "",
    y = "Concentration (#/m3)"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "Conc_measurement_regional_comparison_polymer_size_filtered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)

Figure <- ggplot(per_polymer_unfiltered, aes(x = Polymer, y = Concentration, col=source)) +  
  geom_violin(data = per_polymer_unfiltered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = per_polymer_unfiltered %>% filter(source == "Measurement_NL"), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations in river at regional scale, ", as.character(select_year)),
    subtitle = "Modeled concentrations not filtered for detection limit of measurements",
    x = "",
    y = "Concentration (#/m3)"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "Conc_measurement_regional_comparison_polymer_size_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

Make plot per polymer for continental scale
```{R}
polymers <- unique(concentration_sums$Polymer)

particle_conc_continental_per_polymer_unfiltered <- particles_conc_C_R_2019_per_polymer_unfiltered |>
  filter(Scale == "Continental") |>
  filter(SubCompart == "river") |>
  mutate(source = "SimpleBox") |>
  mutate(Polymer = case_when(
    Polymer == "LDPE" ~ "PE",
    Polymer == "HDPE" ~ "PE",
    Polymer == "NR" ~ "RUBBER",
    Polymer == "SBR" ~ "RUBBER",
    TRUE ~ Polymer
  )) |>
  group_by(RUN, Polymer, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration))

particle_conc_continental_per_polymer_filtered <- particle_conc_C_R_2019_per_polymer_filtered |>
  filter(Scale == "Continental") |>
  filter(SubCompart == "river") |>
  mutate(source = "SimpleBox") |>
  filter(Polymer %in% polymers) |>
  mutate(Polymer = case_when(
    Polymer == "LDPE" ~ "PE",
    Polymer == "HDPE" ~ "PE",
    Polymer == "NR" ~ "RUBBER",
    Polymer == "SBR" ~ "RUBBER",
    TRUE ~ Polymer
  )) |>
  group_by(RUN, Polymer, SubCompart, SubCompartName, source, year, Unit, Scale) |>
  summarise(Concentration = sum(Concentration))

measured_concentrations_polymer <- concentration_sums |>
  mutate(SubCompart = "river",
         Unit = "#/m3",
         SubCompartUnit = paste0(SubCompart, " (", Unit, ")"),
         source = "Measurement_NL")  |>
  filter(Polymer %in% polymers)

# Prepare plot data
per_polymer_filtered <- bind_rows(particle_conc_continental_per_polymer_filtered, measured_concentrations_polymer)
per_polymer_unfiltered <- bind_rows(particle_conc_continental_per_polymer_unfiltered, measured_concentrations_polymer)

Figure <- ggplot(per_polymer_filtered, aes(x = Polymer, y = Concentration, col=source)) +  
  geom_violin(data = per_polymer_filtered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = per_polymer_filtered %>% filter(source == "Measurement_NL"), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations in river at continental scale, ", as.character(select_year)),
    subtitle = "Modeled concentrations filtered for detection limit of measurements",
    x = "",
    y = "Concentration (#/m3)"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "Conc_measurement_continental_comparison_polymer_size_filtered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)

Figure <- ggplot(per_polymer_unfiltered, aes(x = Polymer, y = Concentration, col=source)) +  
  geom_violin(data = per_polymer_unfiltered %>% filter(source == "SimpleBox"), 
              aes(fill = source), alpha = 0.5) + 
  geom_jitter(data = per_polymer_unfiltered %>% filter(source == "Measurement_NL"), 
              aes(col = source), 
              position = position_jitter(width = 0.2), alpha = 1, size = 3) +
  scale_fill_manual(values = Source_type_colors) +
  scale_color_manual(values = Measurement_type_colors) +
  labs(
    title = paste0("Microplastic concentrations in river at continental scale, ", as.character(select_year)),
    subtitle = "Modeled concentrations not filtered for detection limit of measurements",
    x = "",
    y = "Concentration (#/m3)"
  ) +
  plot_theme +  
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))) +
  annotation_logticks(
    sides = "l",  
    short = unit(0.07, "cm"),
    mid = unit(0.07, "cm"),
    long = unit(0.1, "cm"),
    size = 0.25) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL), color = guide_legend(title = NULL))  # Remove legend titles

Figure

ggsave(paste0(figurefolder, "Conc_measurement_continental_comparison_polymer_size_unfiltered_", data_date, ".png"), plot = Figure, width = 20, height = 23, dpi = 1000)
```

# Microplastics in general



