---
title: "LEON-T TWP data analysis"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)


log_warning <- function(warning_message) {
  cat(paste(Sys.time(), "WARNING:", warning_message, "\n"), file = "warnings.log", append = TRUE)
}

log_info <- function(warning_message) {
  cat(paste(Sys.time(), "INFO:", warning_message, "\n"), file = "warnings.log", append = TRUE)
}



```


```{r HPC output}
## internal output file testing:
HPC_output_path <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/HPC_output_test"
HPC_SBout_files <- list.files(HPC_output_path)

HPC_fileName = HPC_SBout_files[1]
HPC_output_path = "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/HPC_output_test"

# function for testing.
# now includes:
# 1. test to see if solver made output for 101 time steps
# ...
check_HPC_output <- function(HPC_fileName = HPC_SBout_files[1],
                             HPC_output_path = "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/HPC_output") {
  
  load(paste0(HPC_output_path,"/",HPC_fileName))
  log_info(paste0(HPC_output_path,"/",HPC_fileName))
  
  test_time1 <-  
    Output |>
    unnest(cols = c(SBoutput)) |> 
    mutate(OutputType = names(SBoutput)) |> 
    filter(OutputType == "DynamicMass") |> 
    unnest(SBoutput) |> 
    ungroup() |> group_by(Polymer) |> 
    count(RUN) |> filter(n<101) |> rename(Timed_length = n)

  
  tryCatch({
    if(length(test_time1$RUN)>0){
    
    warning_message <- "Not 100 years in RUN:\n"
    test_time1_text <- capture.output(print(as.data.frame(test_time1)))
    warning_message <-
      paste(warning_message, paste(test_time1_text, collapse = "\n"),
            "\n See file",paste(HPC_fileName))
    
    warning(warning_message)
    log_warning(warning_message)
    }
  }
  )
}

sapply(HPC_SBout_files,check_HPC_output,HPC_output_path = "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/HPC_output_test")


##### Check contents of TWP files
TWP_pols = data.frame()

for(i in 1:length(TWP_HPC_files)){
  filename <- paste0(HPC_output_path, "/", TWP_HPC_files[i])
  load(filename)
  
  pols <- Output$Polymer
  for(pol in pols){
    # polymer_output <-
    Output |>
      filter(Polymer == pol) |> unnest(cols = c(SBoutput)) |> 
      mutate(OutputType = names(SBoutput)) |> 
      filter(OutputType == "DynamicMass") |> 
      unnest(SBoutput) |> 
      ungroup() |> 
      count(RUN) |> filter(n<101) |> case_when(
        n > 0 ~ paste(filename, "has missing times in RUN", distinct(RUN)),
        .default = "all is fine")
    
    
    
    
    group_by(RUN)
    distinct(RUN) |> n(RUN)
    
    polymer_output <- polymer_output$SBoutput[[1]]
    polymer_mass <- polymer_output$DynamicMass
    NRUNS <- length(unique(polymer_mass$RUN))
    nyear <- length(unique(polymer_mass$time))
    years <- polymer_mass |>
      mutate(Year = time/(365.25*24*3600))
    print(unique(years$Year))
  }
  
  TWP_pols_i <- data.frame(Polymer = (Output$Polymer),
                           NRUNS= NRUNS,
                           filename = filename,
                           Category = "TWP",
                           Nyear = nyear)
  
  TWP_pols <- bind_rows(TWP_pols, TWP_pols_i)
}

##### Check contents of TWP files
Other_pols = data.frame()
i=1
for(i in 1:length(Other_HPC_files)){
  filename <- paste0(HPC_output_path, "/", Other_HPC_files[i])
  load(filename)
  
  pols <- Output$Polymer
  for(pol in pols){
    polymer_output <- Output |>
      filter(Polymer == pol)
    polymer_output <- polymer_output$SBoutput[[1]]
    polymer_mass <- polymer_output$DynamicMass
    NRUNS <- length(unique(polymer_mass$RUN))
    nyear <- length(unique(polymer_mass$time))
    years <- polymer_mass |>
      mutate(Year = time/(365.25*24*3600))
    print(unique(years$Year))
    minrow <- polymer_mass |>
      filter(time == min(time))
  }
  
  Other_pols_i <- data.frame(Polymer = (Output$Polymer),
                             File_no = i,
                             NRUNS= NRUNS,
                             filename = filename,
                             Category = "Other",
                             Nyear = nyear)
  
  Other_pols <- bind_rows(Other_pols, Other_pols_i)
}

```

```{r TWP data}

load(paste0(HPC_output_path,"/",HPC_SBout_files[60]))

Output$SBoutput[1][[1]]$DynamicMass
length(Output$SBoutput[1][[1]]$DynamicMass$time)
plot(Output$SBoutput[1][[1]]$DynamicMass$time,
     Output$SBoutput[1][[1]]$DynamicMass$w1CP)
length(Output$SBoutput[1][[1]]$DynamicConc$Concentrations$time)
plot(Output$SBoutput[1][[1]]$DynamicConc$Concentrations$time,
     Output$SBoutput[1][[1]]$DynamicConc$Concentrations$w1CP) # bij plotten van bijvoorbeeld file 60, ziet de concentratie plot er erg vreemd uit, zou  ook twee stijgende lijnen moeten zijn

pl_emis <- Output$SBoutput[1][[1]]$Input_Emission |> unnest(Emis) |> pivot_wider(names_from = Abbr, values_from = value)
plot(pl_emis$Timed,
     pl_emis$w1RP)


Sel_DPMFA_micro |> 
  unnest(Emis) |> 
  ungroup() |> group_by(Year,Polymer) |> 
  summarise(Emis_kt_year = mean(value)*(3600*24*365.25)/1000000) |> 
  filter(Year < 2020) |> 
  ungroup() |> group_by(Polymer) |> 
  summarise(Emis_kt = sum(Emis_kt_year)) # Emission NR and SBR from 1950 up to 2019 in 1000 ton


mean(as.vector(Material_Parameters_n$data[[1]]$value))

Material_Parameters_n |> distinct(VarName)

MatParAavg <- function(input=Material_Parameters_n$data[[1]]){
  mean(input$value)
}

Material_Parameters_n |> 
  mutate(Average = map_dbl(data, MatParAavg)) |>
  # filter(VarName == "kdeg") |> 
  distinct(nvar,.keep_all = TRUE)

rm(list = objects())

```

```{r DPMFA data}
abspath_EU = "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFA_EU.RData"
abspath_NL = "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFA_NL.RData" # data file location
source_of_interest = "Tyre wear" # a specific source or NA for all
path_parameters_file = "vignettes/CaseStudies/CaseData/Microplastic_variables_v1.xlsx"
TESTING = F # if set to T, using only first 2 runs.

library(tidyverse)
load(abspath_EU)

# Convert to long format
data_long_EU <- 
  DPMFA_sink |> 
  unnest(Mass_Polymer_kt, keep_empty = TRUE) |> 
  pivot_longer(cols=-c(Type, Scale, Source, Polymer, To_Compartment, Material_Type, iD_source, RUN),
               names_to = "Year",
               values_to = "Mass_Polymer_kt") |>
  rename(Cum_Mass_Polymer_kt = Mass_Polymer_kt) |> 
  ungroup() |> 
  group_by(Scale,Source,Polymer,To_Compartment, Material_Type, RUN) |> 
  reframe(
    Mass_Polymer_kt = Cum_Mass_Polymer_kt - lag(Cum_Mass_Polymer_kt, default = 0),
    Year = Year) |> 
  ungroup() |> 
  mutate(Mass_Polymer_kg_s = Mass_Polymer_kt*1000000/(365.25*24*3600)) |> # Convert kt/year to kg/s
  # filter(Material_Type == "micro") |> # Select microplastics only
  mutate(SBscale = ifelse(Scale == "EU", "C", "R"))

data_long_EU |> filter(Mass_Polymer_kg_s < 0)


data_long_EU |> 
  filter(Source == "Tyre wear") |> 
  ungroup() |> 
  group_by(RUN,Year) |> 
  summarise(TotEmission_kt = sum(Mass_Polymer_kt)) |> 
  ungroup() |> 
  group_by(Year) |> 
  summarise(Avg_Emis_kt = mean(TotEmission_kt),
            min_Emis_kt = min(TotEmission_kt),
            max_Emis_kt = max(TotEmission_kt)) |> 
  filter(Year == 2019)
# the result is way too much emission.

data_long_EU |> distinct(Source)
data_long_EU |> 
  filter(Source == "Domestic primary plastic production") |> 
  ungroup() |> 
  group_by(RUN,Year) |> 
  summarise(TotEmission_kt = sum(Mass_Polymer_kt)) |> 
  ungroup() |> 
  group_by(Year) |> 
  summarise(Avg_Emis_kt = mean(TotEmission_kt),
            min_Emis_kt = min(TotEmission_kt),
            max_Emis_kt = max(TotEmission_kt)) |> 
  filter(Year == 2019)

abspath_EU_test <-  "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFA_data_EU2024_11_26.RData"

load(abspath_EU_test)

# Convert to long format
data_long_EU_test <- 
  DPMFA_sink |> unnest(Mass_Polymer_kt, keep_empty = TRUE) |> 
  pivot_longer(cols=-c(Type, Scale, Source, Polymer, To_Compartment, Material_Type, iD_source, RUN),
               names_to = "Year",
               values_to = "Mass_Polymer_kt") |>
  mutate(Mass_Polymer_kg_s = Mass_Polymer_kt*1000000/(365.25*24*3600)) |> # Convert kt/year to kg/s
  # filter(Material_Type == "micro") |> # Select microplastics only
  mutate(SBscale = ifelse(Scale == "EU", "C", "R")) 

data_long_EU_test_TW <- data_long_EU_test|> 
  filter(Source == "Tyre wear") |> 
  ungroup() |> 
  group_by(RUN,Year) |> 
  summarise(TotEmission_kt = sum(Mass_Polymer_kt)) |> 
  ungroup() |> 
  group_by(Year) |> 
  summarise(Avg_Emis_kt = mean(TotEmission_kt),
            min_Emis_kt = min(TotEmission_kt),
            max_Emis_kt = max(TotEmission_kt)) |> 
  filter(Year == 2019)

data_long_EU |> distinct(Source)
data_long_EU |> 
  filter(Source == "Domestic primary plastic production") |> 
  ungroup() |> 
  group_by(RUN,Year) |> 
  summarise(TotEmission_kt = sum(Mass_Polymer_kt)) |> 
  ungroup() |> 
  group_by(Year) |> 
  summarise(Avg_Emis_kt = mean(TotEmission_kt),
            min_Emis_kt = min(TotEmission_kt),
            max_Emis_kt = max(TotEmission_kt)) |> 
  filter(Year == 2019)


rm(list = objects()[-grep("HPC_",objects())])
```

```{r Test with DPMFA_inflow instead of DPMFA_sink}
abspath_EU_test <-  "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFA_data_EU2024_11_26.RData"
load(abspath_EU_test)

######## Use DPMFA inflow instead of sinks, because DPMFA_sink is cumulative over years ######
sinks <- unique(DPMFA_sink$To_Compartment)

# Convert to long format
data_long_EU_test <- DPMFA_inflow|>
  filter(To_Compartment %in% sinks) |>
  unnest(Mass_Polymer_kt, keep_empty = TRUE) |> 
  pivot_longer(cols=-c(Type, Scale, Source, Polymer, To_Compartment, Material_Type, iD_source, RUN),
               names_to = "Year",
               values_to = "Mass_Polymer_kt") |>
  mutate(Mass_Polymer_kg_s = Mass_Polymer_kt*1000000/(365.25*24*3600)) |> # Convert kt/year to kg/s
  # filter(Material_Type == "micro") |> # Select microplastics only
  mutate(SBscale = ifelse(Scale == "EU", "C", "R")) 

data_long_EU_test_TW <- data_long_EU_test|> 
  filter(Source == "Tyre wear") |> 
  ungroup() |> 
  group_by(RUN,Year) |> 
  summarise(TotEmission_kt = sum(Mass_Polymer_kt)) |> 
  ungroup() |> 
  group_by(Year) |> 
  summarise(Avg_Emis_kt = mean(TotEmission_kt),
            min_Emis_kt = min(TotEmission_kt),
            max_Emis_kt = max(TotEmission_kt)) |> 
  filter(Year == 2019)

####### Test with all data ##########

# TO DO: Add test with all DPMFA_EU data, using DPMFA_sink 
```

```{r Material parameters}
load(paste0("/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFAoutput_LEON-T_D3.5_TWP_20241110.RData"))
Material_Parameters_n <- Parameters$Material_Parameters_n
Material_Parameters_long <- Material_Parameters_n |>
  rowwise() |>
  mutate(data = list(data |> mutate(RUN = row_number()))) |>
  ungroup() |>
  unnest(data)

source("vignettes/CaseStudies/f_plot_functions.R")

```

```{r DPMFA_SBoutput files}
load("/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFAoutput_LEON-T_D3.5_TWP_20241126.RData")

DPMFA_sink_micro <- DPMFA_SBoutput$DPMFA_sink_micro |>
  unnest(Emis) |>
  mutate(Mass_kt_y = Mass_kg_s*(365.25*24*3600)/1000000)

# Plot the mean emissions per polymer and per subcompart over time
for(abbr in unique(DPMFA_sink_micro$Abbr)){
  for(pol in unique(DPMFA_sink_micro$Polymer)){
    DPMFA_data <- DPMFA_sink_micro |>
      filter(Abbr == abbr) |>
      filter(Polymer == pol) |>
      group_by(Abbr, Year, Polymer, Subcompartment) |>
      summarise(Mean_kt_y = mean(Mass_kt_y))
    
    plot(DPMFA_data$Year, DPMFA_data$Mean_kt_y, title(paste0(abbr, ", ", pol)))
  }
}

DPMFA_sink_sum <- DPMFA_sink_micro |>
  mutate(id = row_number()) |>
  pivot_wider(names_from = Abbr, values_from = Mass_kt_y, id_expand = FALSE)



load("/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/DPMFAoutput_LEON-T_D3.5_Other_20241126.RData")


```




