---
title: "Recipe data analysis"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
```

## Load output data
```{r Load output data}
folderpath <- "/rivm/r/E121554 LEON-T/03 - uitvoering WP3/Deliverable 3.5/FF_other_test"

filepaths <- list.files(folderpath)

RData_files <- filepaths[endsWith(filepaths, '.RData')]

SS_masses_continental <- tibble()

for(file in RData_files){
  load(paste0(folderpath, "/", file))
  
  SS_masses_allScale <- Output |> 
    unnest(SBoutput) |> 
    mutate(OutputType = names(SBoutput)) |> 
    rename(EmisScale = Scale) |> 
    filter(OutputType == "SteadyStateMass") |> 
    unnest(SBoutput) |> 
    filter(Species != "Unbound") |> 
    ungroup() |> 
    group_by(Polymer, EmisComp, EmisScale, RUN, Scale, SubCompart, Unit) |> 
    summarise(EqMass_SAP = sum(EqMass)) 
  
  SS_masses_continental_pol <- SS_masses_allScale |> 
  filter(EmisScale == "Continental" & (Scale == c("Regional")|Scale == c("Continental"))) |> 
  ungroup() |> 
  group_by(Polymer, EmisComp, EmisScale, RUN, SubCompart, Unit) |> 
  summarise(EqMass_SAP = sum(EqMass_SAP)) |>  # sum nested regional mass and rest of EU mass
  mutate(
    CompartmentFF = case_when(
      SubCompart == "agriculturalsoil" ~ "otherSoil",
      SubCompart == "naturalsoil" ~ "otherSoil",
      #SubCompart == "othersoil" ~ "RoadSoil",
      SubCompart == "othersoil" ~ "otherSoil",
      SubCompart == "cloudwater" ~ "air",
      SubCompart == "lake" ~ "freshwater",
      SubCompart == "river" ~ "freshwater",
      SubCompart == "lakesediment" ~ "freshwatersediment",
      TRUE ~ SubCompart)) |> 
    ungroup() |>
    group_by(Polymer, EmisComp, EmisScale, RUN, CompartmentFF, Unit) |>
    summarise(EqMass_SAP = sum(EqMass_SAP)) |>
    ungroup()
  
  SS_masses_continental <- bind_rows(SS_masses_continental, SS_masses_continental_pol)

  emissions <- Output |> 
    unnest(SBoutput) |> 
    mutate(OutputType = names(SBoutput)) |> 
    rename(EmisScale = Scale) |> 
    filter(OutputType == "Input_Emission") |>
    unnest(SBoutput)
}

```

```{r Make table}

#   group_by(Polymer,CompartmentFF,EmisComp) |> 
#   summarise(FF_SteadyState_avg = mean(EqMass_SAP),
#             FF_SteadyState_std = sd(EqMass_SAP)) |> 
#   mutate(Unit = "kg[ss]/kg[e] seconds")
```

```{r Make figures}
for(pol in unique(SS_masses_continental$Polymer)){
  plot_data <- SS_masses_continental |>
    filter(Polymer == pol) |>
    filter(EqMass_SAP > 10e-25) |>
    filter(!is.na(EqMass_SAP)) |>
    filter(EqMass_SAP != 0)
  
  plot <- ggplot(plot_data, aes(y=EqMass_SAP, x=CompartmentFF))+
    geom_violin()+
      scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x, n = 10),
    labels = scales::trans_format("log10", scales::math_format(10^.x))
  ) +
    facet_wrap(~EmisComp) +
  theme_bw() +
  labs(title = pol,
       x = "Compartment",
       y = "Steady state mass (kg)")
  
  print(plot)
  
   for(emiscomp in unique(plot_data$EmisComp)){
    plot_data_emiscomp <- plot_data |>
      filter(EmisComp == emiscomp)
  }
}
```
