---
title: "Comparison of 2026.3.1 to 2026.4.0"
author: "Joris Quik, Anne Hids"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

# Load function to install SBoo and SBooScripts

```{r setup, include=FALSE}
source("InstallSBoo.R")
```

# Setup for comparison
Below we download 

The below scripts are setup to compare a specific release to the current
version in use. E.g. loaded in R-Studio. (SBoo and SBooScripts). This
can be a release, e.g. the tag or specific branches in SBoo and
SBooScripts.

```{R Specify tag and load}
tag <- "2026.3.1"

#InstallSBoo(Release = tag)
```

Select random substances for testing

```{R select substances, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
substance_current <- read.csv("data/Substances.csv")
substances_other <-  read.csv("SimpleBox/SBooScripts/data/Substances.csv")

substances <- inner_join(substance_current,substances_other)

# Select 5 random substances for each class from substances csv
# and always select the default microplastic.

mp <- substances |>
  filter(Substance == "microplastic")

set.seed(497)

substances <- substances |>
  group_by(ChemClass) |>
  slice_sample(n = 5, replace = FALSE) |>
  ungroup()

substances <- rbind(substances, mp) |>
  distinct()
```

## Calculate for installed version

Calculate first order rate constants for the other version. Here we
apply the new initWorldOther from the current branch as there are
missinng links to the new install folder in the old release. This can be
changed in future comparisons.

```{R warning=FALSE}
# Calculate the kaas 
other_kaas <- data.frame()
  
for(substance in substances$Substance){
 
  source("baseScripts/initWorldOther.R")
    
  other_kaas <- rbind(other_kaas,  World$kaas |>
    mutate(Substance = substance,
           ChemClass = World$fetchData("ChemClass")))
}
```

## Calculate for currently loaded version

Calculate the first order rate constants for the current branch

```{R Clean environment again, include=FALSE}
rm(list = ls()[sapply(ls(), function(x) is.function(get(x)))])
```

```{R Run SB and get advection ks for FLux_work branch, echo=TRUE, message=TRUE, warning=FALSE, results="hide"}
current_kaas <- data.frame()
  
for(substance in substances$Substance){

  source("baseScripts/initWorld.R")
    
  current_kaas <- rbind(current_kaas,  World$kaas |>
                          mutate(Substance = substance,
                                 ChemClass = World$fetchData("ChemClass")))
}
```

# Compare rate constants, k's.

```{R Calculate the differences between ks, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
common_cols <- setdiff(intersect(colnames(current_kaas), colnames(other_kaas)), "k")

kaas_comparison <- merge(other_kaas, current_kaas, by=common_cols, suffixes = c("_Old", "_New"))

kaas_comparison <- kaas_comparison |>
  mutate(diff = k_New-k_Old) |> # If this number is positive, the New_k is higher than the Old_k (higher advection rate with new method)
  mutate(rel_diff = diff/k_New)

changed_kaas_all <- kaas_comparison |>
  filter(diff != 0) |>
  mutate(full_name = paste0("From ", fromSpecies, "_",fromSubCompart, "_", fromScale, 
                            " to ", toSpecies, "_", toSubCompart, "_", toScale))

head(changed_kaas_all)

unique(changed_kaas_all$process)

changed_kaas <- changed_kaas_all |>
  filter(abs(rel_diff) > 0.001) 

unique(changed_kaas$process)
```

# Specific's on differences

No k's have changed, which is to be expected. In release 2026.4.0 the difference 
is in adding two constants: Remove_global and Regional_and_Continental_deepocean. 
These remove the Global compartments and turn Regional and Continental deepocean 
on and off respectively. Because no other updates have been done to SBoo, the k's
should not change when these variables are set to FALSE, which is the default in 
InitWorld.R. 

For more information about the differences between release 2026.3.1 and 2026.4.0 
if these variables are true, see vignettes/Development/Quality control/2026.3.1_comparison_with_Marine_currents.md.