---
title: "Comparison water advection update"
author: "Anne Hids, Joris Quik"
date: "2025-05-27"
output: github_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r init, message=FALSE, warning=FALSE, include=FALSE}

library(tidyverse)
source("baseScripts/initWorld_onlyMolec.R")

f_MutateHelper <- function(varName = "landFRAC",
                           varData = c(0.6000, 0.0050, 0.2700, 0.1000, 0.0250, 0.6000, 0.0050, 0.2700, 0.1000, 0.0250)){
  varWorld <- World$fetchData(varName)
  varWorld[,varName] <- varData
  varWorld <-
    varWorld |> pivot_longer(cols = varName,
                             names_to = "varName",
                             values_to = "Waarde")
  World$mutateVars(varWorld)
  World$UpdateDirty(varName)
  return(World$fetchData(varName))
}

f_AddAbbreviationsSBxlsx <- function(kaas = as_tibble(World$kaas), # table with columns to... and from...
                                     SubcompartmentsMap = # all subcompartments defined for SBoo
                                       c("marinesediment" = "sd2",
                                         "freshwatersediment" = "sd1",
                                         "lakesediment" = "sd0",
                                         "agriculturalsoil" = "s2",
                                         "naturalsoil" = "s1",
                                         "othersoil" = "s3",
                                         "air" = "a",
                                         "deepocean" = "w3",
                                         "sea" = "w2",
                                         "river" = "w1",
                                         "lake" = "w0",
                                         "cloudwater" = "cw"), 
                                     ScalesMap = # all scales defined for SBoo
                                       c("Arctic" = "A",
                                         "Moderate" = "M",
                                         "Tropic" = "T",
                                         "Continental" = "C",
                                         "Regional" = "R"), 
                                     SpeciesMap = # all species defined for SBoo
                                       c("Dissolved" = "D",
                                         "Gas" = "G",
                                         "Large" = "P",
                                         "Small" = "A",
                                         "Solid" = "S",
                                         "Unbound" = "U")
) {
  
  kaas <- kaas |> mutate(
    from = paste0(
      SubcompartmentsMap[fromSubCompart],
      ScalesMap[fromScale],
      SpeciesMap[fromSpecies]
    ),
    to = paste0(
      SubcompartmentsMap[toSubCompart],
      ScalesMap[toScale],
      SpeciesMap[toSpecies]
    )
  )
  
  # kaas <-
  #   kaas |>
  #   mutate(
  #     from =
  #       ifelse((fromScale == "Tropic" | fromScale == "Arctic" | fromScale == "Moderate") &
  #                (fromSubCompart == "marinesediment" | fromSubCompart == "naturalsoil"),
  #              str_replace_all(from, c("sd2" = "sd", "s1" = "s")),
  #              from
  #       )
  #   ) |>
  #   mutate(to = ifelse((toScale == "Tropic" | toScale == "Arctic" | toScale == "Moderate") &
  #                        (toSubCompart == "marinesediment" | toSubCompart == "naturalsoil"), str_replace_all(to, c("sd2" = "sd", "s1" = "s")), to))
  # 
  return(kaas)
}

```

*The advection flow calculations for the freshwater compartments are
revised using a different implementation of advective flows related to
the lake compartment and some other changes (from v2025.4.0 and the
Excel implementation). Below the changes are outlined, and finally a
comparison between the rate constants (k's) of the new and old version
is made.*

## *Update RainOnFreshwater function*

*In the previous version of SimpleBox, RainOnFreshwater was set to 0 for
lake compartments. This is resolved by using the same calculation for
lake as was already used for the river compartments.*

*This was the previous function:*

```{R Old RainOnFreshwater function, include=TRUE}
# RainOnFreshwater
# World$fetchData("RainOnFreshwater") # new implementation provides

RainOnFreshwater <- function (RAINrate, Area, SubCompartName) {
  if (SubCompartName %in% c("river", "lake")) {
    #TODO resolve lake issues in waterflow; for now: old formulas
    if (SubCompartName == "lake"){
      return(0)
    } else {
      # RAINrateToSI is generated from units !
      return(RAINrate * Area)
    }     
  } else    return(NA)
}

CalcVariable <- World$NewCalcVariable("RainOnFreshwater") # load the old function above
# CalcVariable
# CalcVariable$needVars
# CalcVariable$execute()
old <- World$CalcVar("RainOnFreshwater")

```

The updated function now also adds rain on lake freshwater and replaces
the 0's for lake water at global scales with NA's which causes them to
be filtered out automatically.

```{R New RainOnFreshwater function, include=TRUE}
RainOnFreshwater <- function (RAINrate, Area, SubCompartName) {
  if (SubCompartName %in% c("river", "lake")) {
    # RAINrateToSI is generarted from units !
    return(RAINrate * Area)
  } else    return(NA)
}

CalcVariable <- World$NewCalcVariable("RainOnFreshwater") # load the old function above
# CalcVariable
# CalcVariable$needVars
# CalcVariable$execute()
World$CalcVar("RainOnFreshwater")

```

## Optimisation of FracROWatComp

This function calculates the area fraction of river and lake of the
total freshwater area at Regional and Continental scales. This is needed
to calculate how much runoff goes from soil to the different water
compartments.

The new function calculates the same as the old function with two
exceptions: -The function is shorter -There are NA's returned instead of
1's for scales which are not Regional or Continental and the SubCompart
is not river or lake.

```{R Old FracROWatComp function, include=TRUE}
FracROWatComp <- function(all.landFRAC, all.Matrix, Matrix, SubCompartName, ScaleName) {
  compFrac <- all.landFRAC$landFRAC[all.landFRAC$SubCompart == SubCompartName & all.landFRAC$Scale ==  ScaleName]
  all.landFrac <- as_tibble(all.landFRAC)
  all.Matrix <- as_tibble(all.Matrix)
  mergeddata <- left_join(
    x = all.landFRAC,
    y = all.Matrix,
    by = join_by(SubCompart))
  
  if ((Matrix == "water") & (ScaleName %in% c("Regional", "Continental"))) {
    # total landfrac of (fresh) water compartments
    waterFrac <- mergeddata |>
      filter(Matrix == "water" & Scale == ScaleName) |>
      summarise(waterFrac = sum(landFRAC, na.rm = TRUE)) |>
      pull(waterFrac)
    return(compFrac / waterFrac)
  } else {
    return(1)
  }
}


CalcVariable <- World$NewCalcVariable("FracROWatComp") # load the old function above
# CalcVariable
# CalcVariable$needVars
# CalcVariable$execute()
old <- World$CalcVar("FracROWatComp")

```

```{R New FracROWatComp function, include=TRUE}
FracROWatComp <- function(all.landFRAC, all.Matrix, Matrix, SubCompartName, ScaleName) {
  if ((Matrix == "water") & (ScaleName %in% c("Regional", "Continental"))) {
    compFrac <- all.landFRAC$landFRAC[all.landFRAC$SubCompart == SubCompartName & all.landFRAC$Scale ==  ScaleName]
    mergeddata <- merge(all.landFRAC,all.Matrix)
    waterFrac = sum(mergeddata$landFRAC[mergeddata$Matrix == "water" & mergeddata$Scale ==  ScaleName])
    return(compFrac / waterFrac)
  } else {
    return(NA)
  }
}

CalcVariable <- World$NewCalcVariable("FracROWatComp") # load the old function above
# CalcVariable
# CalcVariable$needVars
# CalcVariable$execute()
World$CalcVar("FracROWatComp")

```

## *Update ContRiver2Reg*

For the 'river' SubCompart at 'Continental' Scale, the flow from
Continental to Regional river is now calculated as:

(sum of all runoff + the sum of all rain on freshwater) \*
dischargefraction between regional and continental scale.

*The previously used function can be seen in the chunk below*

```{R Old ContRiver2Reg, include=TRUE}

f_MutateHelper(varName = "dischargeFRAC",
               varData = c(0.1,0))

x_ContRiver2Reg <- function (ScaleName, SubCompartName, 
                             all.RunoffFlow, RainOnFreshwater, 
                             dischargeFRAC, LakeFracRiver){
  switch (ScaleName,
          "Continental" = {
            switch (SubCompartName,
                    "river" = { 
                      SumRainRunoff <- sum(all.RunoffFlow$RunoffFlow[all.RunoffFlow$Scale == "Continental"])
                      River2sea  <- RainOnFreshwater + SumRainRunoff * (1-dischargeFRAC)
                      Lake2River <- LakeFracRiver * River2sea
                      
                      return((RainOnFreshwater + SumRainRunoff + Lake2River) * dischargeFRAC)
                    },
                    return(NA)
            )
          },
          return(NA)
  )
}
# World$fetchData("RunoffFlow")
CalcVariable <- World$NewCalcVariable("x_ContRiver2Reg") # load the old function above
# World$fetchData("dischargeFRAC")

# World$fetchData("dischargeFRAC")

# World$fetchData("Runoff")

old <- World$CalcVar("x_ContRiver2Reg")



```

The updated function is simpler, more straightforward. the outflow
depends purely on the fraction of Rain and Runoff going to the regional
scale.

```{R New ContRiver2Reg, include=TRUE}
x_ContRiver2Reg <- function (ScaleName, SubCompartName, 
                             all.RunoffFlow, all.RainOnFreshwater, 
                             dischargeFRAC){
  
  switch (ScaleName,
          "Continental" = {
            switch (SubCompartName,
                    "river" = {
                      SumRainRunoff <- sum(all.RunoffFlow$RunoffFlow[all.RunoffFlow$Scale == ScaleName])+
                        sum(all.RainOnFreshwater$RainOnFreshwater[all.RainOnFreshwater$Scale == ScaleName])
                      # River2sea  <- RainOnFreshwater + SumRunoff * (1-dischargeFRAC)
                      # Lake2River <- LakeFracRiver * River2sea
                      
                      return((SumRainRunoff) * dischargeFRAC)
                    },
                    return(NA)
            )
          },
          return(NA)
  )
  
}
CalcVariable <- World$NewCalcVariable("x_ContRiver2Reg") # load the old function above
new <- World$CalcVar("x_ContRiver2Reg")

diff <- old$x_ContRiver2Reg - new$x_ContRiver2Reg
diff
# diff/old$x_ContRiver2Reg
# diff/new$x_ContRiver2Reg

```

The difference between the two functions is because in previous
itteration LakeFracRiver was used (World\$fetchData("LakeFracRiver")) to
calculate the flow from up stream fresh water (e.g. lake) (w0) to the
major downstream freshwater compartment, e.g. river (w1). This is now
done based on the calculated RunoffFlow going to w0 plus Rain on w0.
Details on the move away from using LakeFracRiver, see below.

## Update LakeOut function

The Lake compartment (w0) is an upstream compartment within a Scale that
has outflow to fresh water (w1). The outflow is dependent on the
fraction runoff going to lake (FracROWatComp) and the direct Rain on
lake fresh water (RainOnFreshwater). The flow from lake to river at
Regional and Continental scale is now calculated as:

*RainOnFreshwater + FracROWatComp\*SumRunoff*

```{R Old LakeOut function, include=TRUE}
x_LakeOutflow <- function(all.x_RiverDischarge, 
                           all.x_ContRiver2Reg, 
                           LakeFracRiver, 
                           ScaleName){
  x_RiverDischarge <- all.x_RiverDischarge$flow[all.x_RiverDischarge$fromScale==ScaleName]
  if(ScaleName == "Continental") {
    return(LakeFracRiver * x_RiverDischarge)
  } 
  if(ScaleName == "Regional"){
    x_ContRiver2Reg <- all.x_ContRiver2Reg$flow
    return(LakeFracRiver * (x_RiverDischarge + x_ContRiver2Reg))
  } 
  else NA
}


CalcVariable <- World$NewCalcVariable("x_LakeOutflow") # load the old function above
old <- World$CalcVar("x_LakeOutflow")

```

```{R New LakeOut function, include=TRUE}
x_LakeOutflow <- function(RainOnFreshwater,
                           all.RunoffFlow,
                           FracROWatComp,
                       SubCompartName,
                           ScaleName){
  switch(SubCompartName, # if this is coded with if statement it fails as SubCompartName for Arctic is NA
          "lake" = {
            SumRunoff <- sum(all.RunoffFlow$RunoffFlow[all.RunoffFlow$Scale == ScaleName])
            return(RainOnFreshwater + FracROWatComp*SumRunoff)
          },
          NA
  )
}

CalcVariable <- World$NewCalcVariable("x_LakeOutflow") # load the old function above
World$CalcVar("x_LakeOutflow")


# World$CalcVar("FracROWatComp")

```

The new implementation results in a lower LakeOut flow because it is not
fixed to a set fraction of the river discharge, but calculated based on
the fraction of Runoff going to lake which is based on the surface are
of the lake versus surface area of the river fresh water compartment.

# Compare new with previous implementation

*The below scripts should be run to compare two versions of SBoo. This
uses a function for downloading and ordering the folders needed to
compare.*

*TO DO: fetch development at a certain date/commit hash instead of most
recent version in a branch. This would ensure consequent outcomes of
this comparison, no matter when the script is run or if a branch is
deleted.*

```{R Specify directories, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
source("vignettes/Development/Quality control/ComparisonFunctions.R")

# tag <- "2025.04.0"
# branch_sboo <- "FLux_work"
# branch_sbooscripts <- "Fluxwork"
# dest_folder <- "/rivm/n/hidsa/Documents/Temp"
folderpaths <- CompareFilesPrep(Release = "2025.04.0", # specify the tag to compare to
                                Test_SBoo = "FLux_work", # the branch name
                                Test_SBooScripts = "Fluxwork", # the branch name
                                Temp_Folder = "C:/Temp") # test folder

# Define branches to test
# branches <- c("main", "FLux_work")

# Specify file paths for saving results
# result_files <- paste0("results_", branches, ".rds")

# Directory of your Git repository (modify this path to the correct repository location)
# script_dir <-getwd()
# repo_dir <- file.path(getwd(), "..", "SBoo")
```

*As advection processes do not depend on substance variables, we only
need to compare the advection flows for one substance, in this case
1-aminoanthraquinone.*

```{R Specify substance, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
substance_names <- "1-aminoanthraquinone" 
substances <- read.csv("data/Substances.csv")
substances <- substances |>
  filter(ChemClass == "")

substances <- substances[c(1,2),]
```

```{R Specify temporary directory, include = FALSE}
# Specify where the downloaded versions of sboo and sbooscripts should be saved to
# dest_folder <- "/rivm/n/hidsa/Documents/Temp"
```

```{R Specify which tag and branch to compare}
# tag <- "2025.04.0"
# branch_sboo <- "FLux_work"
# branch_sbooscripts <- "Fluxwork"
```

```{R Switch to SBoo Development branch, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
# source("vignettes/Development/Quality control/ComparisonFunctions.R")

# folderpaths <- CompareFilesPrep(Release = tag,
# Test_SBoo = branch_sboo,
# Test_SBooScripts = branch_sbooscripts,
# Temp_Folder = dest_folder)
```

*First remove all functions from the global environment to avoid errors*

```{R Clean environment, include=FALSE}
rm(list = ls()[sapply(ls(), function(x) is.function(get(x)))])
```

## Main version / development branch

```{R Run SB and get advection ks for development, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
# Save the original working directory for later
original_wd <- getwd()

# Change the wd to the wd of the main branches
setwd(paste0(folderpaths[1], "/SBooScripts"))

# Calculate the kaas 
main_kaas <- data.frame()
# main_solution <- "start"

for(i in 1:nrow(substances)){
  # Get the substance type
  subst_row <- substances[i, ]
  
  substance <- subst_row$Substance
  cc <- subst_row$ChemClass
  
  if(substance == 'microplastic' | substance == "TRWP"){
    source("baseScripts/initWorld_onlyPlastics.R")
  } else if(cc == "particle"){
    source("baseScripts/initWorld_onlyParticulate.R")
  } else{
    source("baseScripts/initWorld_onlyMolec.R")
  }
  
  kaas <- World$kaas |>
    # filter(process == "k_Advection") |>
    mutate(Substance = substance)
  
  main_kaas <- rbind(main_kaas, kaas)
  
  
  if(World$fetchData("ChemClass") == "particle"){
    emissions <- data.frame(Abbr = c("aRS", "s2RS", "w1RS"), 
                            Emis = c(10000, 10000, 10000)) # convert 1 t/y to si units: kg/s
    emissions <- emissions |>
      mutate(Emis = Emis * 1000 / (365 * 24 * 60 * 60))
  } else {
    emissions <- data.frame(Abbr = c("aRU", "s2RU", "w1RU"), 
                            Emis = c(10000, 10000, 10000)) # convert 1 t/y to si units: mol/s
    emissions <- emissions |>
      mutate(Emis = Emis * 1000 / (365 * 24 * 60 * 60))
  }
  
  World$NewSolver("SteadyStateSolver")
  World$Solve(emissions)
  
  solution <- World$Masses()
  names(solution)[names(solution) == "Mass_kg"] <- "main_Mass_kg"
  solution$Substance <- substances$Substance[i]
  
  if(i == 1) main_solution <- solution else {
    main_solution <- merge(main_solution,solution,all = TRUE)}
  
  solution_conc <- World$Concentration()
  names(solution_conc)[names(solution_conc) == "Concentration"] <- "main_Conc."
  solution_conc$Substance <- substances$Substance[i]
  if(i == 1) main_solution_conc <- solution_conc else {
    main_solution_conc <- merge(main_solution_conc,solution_conc,all = TRUE)}
  
  ################################################################3
  # for mass balance
  
    RateConstants <- f_AddAbbreviationsSBxlsx()  |>
    filter(!(toScale %in% c("Regional", "Continental") & toSubCompart == "deepocean")) # remove k's for deepocean at continental and regional scale
  
  # Remove the unbound compartments if the substance is particle/microplastic
  if(cc == "particle"){
    RateConstants <- RateConstants |>
      filter(fromSpecies != "Unbound") |>
      filter(toSpecies != "Unbound")
  }
  
  Masses <- World$Masses()
  
  # Remove the unbound compartments if the substance is particle/microplastic
  if(cc == "particle"){
    Masses <- Masses |>
      filter(!endsWith(Abbr, "U"))
  }
  
  MassBalanceTest <- 
    RateConstants |> 
    full_join(Masses, by = join_by(from == Abbr)) |> 
    rename(fromMass_kg = Mass_kg) |> 
    mutate(ProcessMassFlow_kg_s = fromMass_kg * k)
  
  # test <- World$exportEngineR()
  
  Removal <- 
    MassBalanceTest |> 
    mutate(Type = case_when(
      process == "k_Degradation" ~ "Removal",
      process == "k_Adsorption" ~ "InterMedia",
      process == "k_Advection" ~ "InterMedia",
      process == "k_Deposition" ~ "InterMedia",
      process == "k_Desorption" ~ "InterMedia",
      process == "k_Erosion" ~ "InterMedia",
      process == "k_Escape" ~ "Removal",
      process == "k_Resuspension" ~ "InterMedia",
      process == "k_Leaching" ~ "Removal",
      process == "k_Runoff" ~ "InterMedia",
      process == "k_Sedimentation" ~ "InterMedia",
      process == "k_Volatilisation" ~ "InterMedia",
      process == "k_Burial" ~ "Removal",
      TRUE ~ NA
    )) |> filter(Type == "Removal") |> 
    group_by(from) |> 
    summarise(Removal_kg_s = sum(ProcessMassFlow_kg_s ))
  
  MassBalanceTest2 <-
    MassBalanceTest |> pivot_wider(id_cols = to, names_from = from, values_from = ProcessMassFlow_kg_s,
                                   values_fn = sum,
                                   values_fill = 0) 
  
  Trans_from <-
    MassBalanceTest2 |> select(-to) |>  ungroup() |> 
    summarise(across(everything(),sum)) |> t()
  
  colnames(Trans_from) <- "Trans_from"
  
  Trans_to <-
    MassBalanceTest2 |> select(-to) |>  rowwise() |>
    mutate(Trans_to = sum(c_across(everything()))) |> select(Trans_to)
  
  #Trans_to <- as.matrix(Trans_to)
  
  trans_to_rownames <- MassBalanceTest2$to
  rownames(Trans_to) <- trans_to_rownames
  
  Trans_from_aligned <- Trans_from[rownames(Trans_to), , drop = FALSE]
  MassBalanceCheck <- cbind(Trans_to, Trans_from_aligned)
  
  MassBalanceCheck$Compartment <- row.names(MassBalanceCheck)
  MassBalanceCheck <- merge(MassBalanceCheck,World$Emissions(),by.x = "Compartment",by.y = "Abbr")
  MassBalanceCheck <- merge(MassBalanceCheck,Removal,by.x = "Compartment",by.y = "from")
  
  MassBalanceCheck <- 
    MassBalanceCheck |> 
    mutate(
      Diff_Flows = (Trans_to+Emission_kg_s)-(Trans_from+Removal_kg_s)
    )
  

  
}

source("C:/GitProjects/SBooScripts/vignettes/Development/Quality control/MassBalanceFunction.R")

MassBalanca_1 <- f_mbalans(substance_name = substance)  


```

## *New implementation.*

```{R Clean environment again, include=FALSE}
rm(list = ls()[sapply(ls(), function(x) is.function(get(x)))])
```

```{R Run SB and get advection ks for FLux_work branch, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}
# Change the wd to the wd of the main branches
setwd(paste0(folderpaths[2], "/SBooScripts"))

test_kaas <- data.frame()
test_solution <- NA

for(i in 1:nrow(substances)){
  # Get the substance type
  subst_row <- substances[i, ]
  
  substance <- subst_row$Substance
  cc <- subst_row$ChemClass
  
  if(substance == 'microplastic' | substance == "TRWP"){
    source("baseScripts/initWorld_onlyPlastics.R")
  } else if(cc == "particle"){
    source("baseScripts/initWorld_onlyParticulate.R")
  } else{
    source("baseScripts/initWorld_onlyMolec.R")
  }
  
  #   mutLandFrac <- World$fetchData("landFRAC")
  # mutLandFrac$landFRAC <- c(0.6000, 0.0050, 0.2700, 0.1000, 0.0250, 0.6000, 0.0050, 0.2700, 0.1000, 0.0250)
  # mutLandFrac <-
  #   mutLandFrac |> pivot_longer(cols = "landFRAC",
  #                             names_to = "varName",
  #                             values_to = "Waarde")
  # World$mutateVars(mutLandFrac)
  # World$UpdateDirty("landFRAC")
  
  
  kaas <- World$kaas |>
    # filter(process == "k_Advection") |>
    mutate(Substance = substance)
  
  test_kaas <- rbind(test_kaas, kaas)
  
  if(World$fetchData("ChemClass") == "particle"){
    emissions <- data.frame(Abbr = c("aRS", "s2RS", "w1RS"), 
                            Emis = c(10000, 10000, 10000)) # convert 1 t/y to si units: kg/s
    emissions <- emissions |>
      mutate(Emis = Emis * 1000 / (365 * 24 * 60 * 60))
  } else {
    emissions <- data.frame(Abbr = c("aRU", "s2RU", "w1RU"), 
                            Emis = c(10000, 10000, 10000)) # convert 1 t/y to si units: mol/s
    emissions <- emissions |>
      mutate(Emis = Emis * 1000 / (365 * 24 * 60 * 60))
  }
  
  World$NewSolver("SteadyStateSolver")
  World$Solve(emissions)
  
  solution <- World$Masses()
  names(solution)[names(solution) == "Mass_kg"] <- "test_Mass_kg"
  solution$Substance <- substances$Substance[i]
  if(i == 1) test_solution <- solution else {
    test_solution <- merge(test_solution,solution,all = TRUE)}
  
  solution_conc <- World$Concentration()
  names(solution_conc)[names(solution_conc) == "Concentration"] <- "test_Conc."
  solution_conc$Substance <- substances$Substance[i]
  if(i == 1) test_solution_conc <- solution_conc else {
    test_solution_conc <- merge(test_solution_conc,solution_conc,all = TRUE)}
  
MassBalanca_ <- f_mbalans(substance_name = substance)  

}

setwd(original_wd)

```

## *Compare the k values for each of the substances*

```{R Calculate the differences between ks, results ="hide", echo=TRUE, message=FALSE, warning=FALSE}

common_cols <- setdiff(intersect(colnames(main_kaas), colnames(test_kaas)), "k")

kaas_comparison <- 
  merge(main_kaas, test_kaas, by=common_cols, suffixes = c("_Old", "_New")) |>
  mutate(diff = k_New-k_Old) |> # If this number is positive, the New_k is higher than the Old_k (higher advection rate with new method)
  mutate(rel_diff = diff/k_Old)

kaas_comparison |>
  # filter(diff != 0) |>
  mutate(full_name = paste0("From ", fromSubCompart, "_", fromScale, " to ", toSubCompart, "_", toScale)) |> 
  filter(fromScale == "Tropic" & fromSubCompart == "deepocean")


# solutions

solution_comparison <- 
  merge(main_solution,test_solution) |> 
  mutate(diff = test_Mass_kg-main_Mass_kg) |> 
  mutate(rel_diff = diff/main_Mass_kg)

con_solution_comparison <- 
  merge(main_solution_conc,test_solution_conc) |> 
  mutate(diff = test_Conc.-main_Conc.) |> 
  mutate(rel_diff = diff/main_Conc.)

changed_mass <- solution_comparison |>
  filter(diff != 0) 

```

```{R Plot the differences between ks, include=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# mean_diffs <- kaas_comparison |>
#   mutate(fromname = paste0(fromSubCompart, "_", fromScale)) |>
#   mutate(toname = paste0(toSubCompart, "_", toScale)) |>
#   # mutate(diff = ifelse(diff == 0, NaN, diff)) |>
#   filter(diff != 0)


changed_kaas <- kaas_comparison |>
  filter(diff != 0) |>
  mutate(full_name = paste0("From ", fromSubCompart, "_", fromScale, " to ", toSubCompart, "_", toScale)) |> 
  mutate(fromname = paste0(fromSubCompart, "_", fromScale)) |>
  mutate(toname = paste0(toSubCompart, "_", toScale))

# ggplot(changed_kaas, mapping = aes(x = toname, y = fromname, color = diff)) + 
#   geom_point() + 
#   scale_color_gradient2(
#     low = "blue",    # Colors for negative values
#     mid = "grey",   # Neutral point at zero
#     high = "red",  # Colors for positive values
#     midpoint = 0,   # Center the scale at zero
#     limits = c(-max(abs(changed_kaas$diff)), max(abs(changed_kaas$diff)))  # Ensure symmetric scale
#   ) +
#   labs(
#     title = "Difference between old and new advection k's",
#     x = "To",  
#     y = "From",  
#     color = "Difference"  
#   ) +
#   theme(
#     axis.text.x = element_text(angle = 45, hjust = 1), 
#     panel.grid.major = element_line(size = 0.2, color = "gray90"),  
#     panel.background = element_blank() 
#   )

ggplot(changed_kaas, mapping = aes(x = toname, y = fromname, color = rel_diff)) + 
  geom_point(aes(shape = Substance)) + 
  labs(
    title = "Relative difference between old and new advection k's",
    x = "To",  
    y = "From",  
    color = "Relative difference"  
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    panel.grid.major = element_line(size = 0.2, color = "gray90"),
    panel.background = element_blank()  
  )

table_for_display <- changed_kaas |>
  select(fromScale, fromSubCompart, toScale, toSubCompart, Substance, k_Old, k_New, diff, rel_diff) |>
  mutate(diff = format(diff, scientific = TRUE, digits = 2)) |>
  mutate(rel_diff = format(rel_diff, scientific = TRUE, digits = 2))

knitr::kable(table_for_display)


ggplot(solution_comparison, mapping = aes(x = Abbr, y = diff, fill = Substance)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Difference between old and new steadystate mass",
    x = "Compartment",  
    y = "(Mass_new - Mass_old)"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    panel.grid.major = element_line(size = 0.2, color = "gray90"),
    panel.background = element_blank()  
  )

ggplot(solution_comparison, mapping = aes(x = Abbr, y = rel_diff, fill = Substance)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Relative difference between old and new steadystate mass",
    x = "Compartment",  
    y = "(Mass_new-Mass_old)/Mass_old"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    panel.grid.major = element_line(size = 0.2, color = "gray90"),
    panel.background = element_blank()  
  )

ggplot(con_solution_comparison, mapping = aes(x = Abbr, y = rel_diff, fill = Substance)) + 
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    title = "Relative difference between old and new steadystate concentrations",
    x = "Compartment",  
    y = "(New-Previous)/Previous"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    panel.grid.major = element_line(size = 0.2, color = "gray90"),
    panel.background = element_blank()  
  )




```

*From these figures and the table we can see that the flows between
Continental sea and Moderate sea are slightly higher in the new
implementation than in the old implementation.*

*The flows from lake to river on Regional and Continental scale changed
the most; relatively a fraction of +- -0.3. So the flow is lower in the
new implementation than in the old implementation.*
