---
title: "Dry Deposition in SB4nano v4.04 "
author: "Valerie de Rijk"
date: "`r Sys.Date()`"
output: github_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::knit_meta()
knitr::opts_chunk$set(echo = TRUE)
## impossible to generalise? projectRoot <- paste(getwd(), "..", sep = "/")
# projectRoot <- paste(getwd(), "..", "..", sep = "/")
# knitr::opts_knit$set(root.dir = projectRoot) #assuming vignette is in a direct subfolder of the project
```

```{r warning=FALSE}
#We need to initialize, by default a molecular substance is selected
Potential_substances <- c("1-aminoanthraquinone", # no class
                          "1-HYDROXYANTHRAQUINONE", # acid
                          "1-Hexadecanamine, N,N-dimethyl-", # base
                          "1-Chloro-2-nitro-propane", # neutral
                          "Sb(III)", # metal
                          "nAg_10nm", # nanoparticle (class particle) #not in substancelist?
                          "microplastic") # microplastic (class particle)
substance <- Potential_substances[6]
#create the relevant world for the substance selected
source("baseScripts/initWorld_onlyParticulate.R")
#source("baseScripts/initworld_onlyMolec.R")

length(unique(World$kaas$process))

ProcessNanoFunctions <- c("k_Advection", "k_Burial",
                         "k_HeteroAgglomeration.a", "k_HeteroAgglomeration.wsd",
                         "k_CWscavenging", "k_Degradation",
                         "k_DryDeposition", "k_Erosion", "k_Escape",
                         "k_Leaching", "k_Resuspension", "k_Runoff", "k_Sedimentation",
                        "k_WetDeposition")




ProcessNanoFunctions[!ProcessNanoFunctions %in% unique(World$kaas$process)]

unique(World$kaas$process)
World$fetchData("AEROresist")
World$fetchData("rad_species")
World$fetchData("RadS")
World$fetchData("RadCOL")
World$fetchData("RadCP")
#World$moduleList[["k_DryDeposition"]]$execute()
#World$moduleList[["k_DryDeposition"]]$execute(debugAt = list())
#df$execute(debugAt = list(Scale = "Regional", SubCompart = "lake"))
World$fetchData("FricVel")
World$fetchData("SettlingVelocity")
World$fetchData("gamma.surf")
```


```{r data xlsx and R}
#Comparing K's from R model to K's from excel model
library(openxlsx)
library(tidyverse)
#read in K matrix from excel
SBExcelName <- paste0("vignettes/Development/Quality control/SBExcel/SimpleBox4plastics_rev009-1_",substance,".xlsx") 

SBexcel.K <- read.xlsx(SBExcelName,
                  colNames = FALSE,
                  namedRegion = "K")
SBexcel.Names <- read.xlsx(SBExcelName,
                  colNames = FALSE,
                  namedRegion = "box_names")

colnames(SBexcel.K) <- SBexcel.Names

SBexcel.K$to <-  as.character(SBexcel.Names)

SBexcel.K <- pivot_longer(SBexcel.K, cols =  as.character(SBexcel.Names), values_to = "k", names_to = "from")

length(SBexcel.K$k)

#adding "from" and "to" acronyms to the R K matrix
kaas <- as_tibble(World$kaas)
unique(kaas$fromScale)
unique(kaas$fromSubCompart)

#R version does not us the acronyms of the excel version, set-up to convert them
#Note: this map creates the wrong acronym for soil and sediment at global scale, this is fixed afterwards
accronym_map <- c("marinesediment" = "sd2",
                "freshwatersediment" = "sd1",
                "lakesediment" = "sd0", #SB Excel does not have this compartment. To do: can we turn this off (exclude this compartment) for testing?
                "agriculturalsoil" = "s2",
                "naturalsoil" = "s1",
                "othersoil" = "s3",
                "air" = "a",
                "deepocean" = "w3",
                "sea" = "w2",
                "river" = "w1",
                "lake" = "w0", 
                "cloudwater" = "cw")

accronym_map2 <- c("Arctic" = "A",
                   "Moderate" = "M",
                   "Tropic" = "T",
                   "Continental" = "C",
                   "Regional" = "R")

accronym_map3 <- c("Dissolved" = "D", 
                   "Gas" = "G", 
                   "Large" = "P", 
                   "Small" = "A",
                   "Solid" = "S", 
                   "Unbound" = "U")

# kaas |> filter(fromScale == "Tropic" & process == "k_Degradation") |> print(n=50)

kaas <- kaas |> mutate(from =  paste0(accronym_map[fromSubCompart], 
                            accronym_map2[fromScale], 
                            accronym_map3[fromSpecies]),
               to = paste0(accronym_map[toSubCompart], 
                           accronym_map2[toScale], 
                           accronym_map3[toSpecies]))

# kaas$from <- paste0(accronym_map[kaas$fromSubCompart], accronym_map2[kaas$fromScale])

# kaas$to <- paste0(accronym_map[kaas$toSubCompart], accronym_map2[kaas$toScale])

# Issue that compartments sediment and soil at global scale in excel have sd and s as acronyms instead of sd2 and s1 , happens in this case as well

#"sd2"="sd","s1"="s", "s2 =s", "s3 = s", "sd0 = sd", "sd1 = sd1")
#("sd2"="sd","s1"="s")
kaas <-
  kaas |>
  mutate(from =
                   ifelse((fromScale == "Tropic" | fromScale == "Arctic" | fromScale == "Moderate") &
                            (fromSubCompart == "marinesediment" | fromSubCompart == "naturalsoil"),
                          str_replace_all(from, c("sd2"="sd","s1"="s")),
                          from)) |>
  mutate(to = ifelse((toScale == "Tropic" | toScale == "Arctic" | toScale == "Moderate") &
                       (toSubCompart == "marinesediment" | toSubCompart == "naturalsoil"), str_replace_all(to, c("sd2"="sd","s1"="s")), to))



diagonal_excel <- SBexcel.K[SBexcel.K$from == SBexcel.K$to,] #all the diagonals in excel are negative values -> sums of all the "froms" of that compartment

#filter out dissolved and gas processes

filtered_excel <- diagonal_excel[!endsWith(diagonal_excel$from, "D"), ]
filtered_excel <- filtered_excel[!endsWith(filtered_excel$from, "G"), ]

#diagonal_excel <- filtered_excel

#filter out molecular (unbound) state
#R model has k values per process, not per box. For the "diagonal" ("from = to") boxes, this is different than in the excel version. summing all the "froms" here to be able to compare them with excel matrix. This should result in one value for each compartment (scale-subcomp-species combo)

diagonal_R <-aggregate(k ~ from, data = kaas, FUN = sum) 
print(diagonal_R$from)
filtered_R <- diagonal_R[!endsWith(diagonal_R$from, "U"), ]2

#diagonal_R <- filtered_R
      
```

```{r diagonal}
#Check for any differences in what compartments there are between versions
# diagonal_R$from[!diagonal_R$from %in% diagonal_excel$from] # "sd0C" "sd0R" were added in sboo v1
library (ggplot2)
library(plotly)
filtered_R$from[!filtered_R$from %in% filtered_excel$from]
# diagonal_excel$from[!diagonal_excel$from %in% diagonal_R$from] #all excel diagonals are in those of R
filtered_excel$from[!filtered_excel$from %in% filtered_R$from]
ifelse(length(diagonal_R$k)==length(diagonal_excel$k) ,
       print("ok"), stop("too many compartment combo's")) 

#Single dataframe with both the R and excel diagonals
merged_diagonal <- merge(filtered_R, filtered_excel, by = "from", suffixes = c("_R", "_Excel")) 
merged_diagonal$k_Excel <- -merged_diagonal$k_Excel #Turning the "negative" values from the Excel matrix into positive ones
merged_diagonal$diff <- merged_diagonal$k_R - merged_diagonal$k_Excel 

#Plot of differences of the diagonals per compartment
plot <- ggplot(merged_diagonal, aes(x = from, y = diff)) +
  geom_boxplot()

print(plot)



sorted_diff <- merged_diagonal[order(abs(merged_diagonal$diff), decreasing = TRUE), ]
print(sorted_diff$from)
```


```{r rate_constants}
#Dataframe of all other boxes

# kaas |> filter(to != from)


kaas2 <- kaas |>  
  filter(from != to) |> #filtering the diagonals ou
  group_by(from, to) %>% summarize(k = sum(k)) #R version sometimes has multiple k's per fromto box; excel only has the summed k's per box
kaas2 <- kaas2[!endsWith(kaas2$from, "U"), ]
kaas2$fromto <- paste(sep = "_", kaas2$from, kaas2$to)

SBexcel.K <- filter(SBexcel.K, k != 0 & SBexcel.K$from != SBexcel.K$to)
SBexcel.K <- SBexcel.K |>
  filter(!endsWith(from, "D") & !endsWith(from, "G")) |>
  filter(!endsWith(to, "D") & !endsWith(to, "G"))
SBexcel.K$fromto <- paste(sep = "_", SBexcel.K$from, SBexcel.K$to)

SBexcel.K$fromto[!SBexcel.K$fromto %in% kaas2$fromto] # No xlsx missing


kaas2$fromto[!kaas2$fromto %in% SBexcel.K$fromto] # more k's in SBoo than in SBxl

mergedkaas <- merge(kaas2, SBexcel.K, by = c("from", "to"), suffixes = c("_R", "_Excel"))

mergedkaas$diff <- mergedkaas$k_R - mergedkaas$k_Excel #compare R k to Excel K

mergedkaas <- as_tibble(mergedkaas) |> mutate(relDif = diff/k_R)

sorted_diff_abs <- mergedkaas[order(abs(mergedkaas$diff), decreasing = TRUE), ]


# Calculate relative differences
mergedkaas <- mergedkaas %>% mutate(relDif = diff / k_R)

# Sort compartments by relative difference from highest to lowest
sorted_diff_rel <- mergedkaas[order(abs(mergedkaas$relDif), decreasing = TRUE), ]

# Print compartments sorted by relative difference
print("Compartments sorted by relative difference:")
print(sorted_diff_rel$from)

#Column "diff" in df "mergedkaas" shows the difference between the R k output and the k's in Excel. 

#Visualize the diff per process in boxplots: which compartments (fromto boxes) have the largest differences between R and the excel model?

#Diff per "from" compartment
ggplot(mergedkaas, aes (x = from, y = diff)) +
  geom_boxplot()

#Diff per "to" compartment
ggplot(mergedkaas, aes (x = to, y = diff)) +
  geom_boxplot()

# "To" and "from" in one plot
ggplot(mergedkaas, aes(x = to, y = from, color = abs(diff))) + 
  geom_point() +
  scale_color_gradient(low = "green", high = "red", trans = "log10") 


ggplot(mergedkaas, aes(x = to, y = from, color = abs(relDif))) + 
  geom_point() +
  scale_color_gradient(low = "green", high = "red") 
#If you want to inspect per process instead of fromto box: look at the original kaas dataframe
kaas |> filter(from == "aAS")


```
